### ISSUE TITLE
Deploy on gh-pages

### ISSUE THREAD

**Issue by isuruAb** [CISSUSL/Fujiyama#7]
**Actual Behaviour**

Application is not hosted any where and users cant send preview link with PRs

**Expected Behaviour**

There should be a way that users can provide preview link with their PRs

**Would you like to work on the issue?**

Yes

**Comment by WThamira** [comment]
done this. 
use [preview](https://cissusl.github.io/Fujiyama/)

**Comment by isuruAb** [comment]
@WThamira  Add this gh-pages live URL into Documentation please
